In [ ]:
import pandas as pd
df = pd.read_csv("professors_dataset.csv")

df.head()

,professor_id,name,email,expertise_domains,availability
0,1,Dr. Blake Williams,prof1@university.edu,"Software Engineering, Machine Learning, Intern...",Available
1,2,Dr. Riley Rodriguez,prof2@university.edu,"Data Science, Blockchain, Computer Vision",Available
2,3,Dr. Avery Moore,prof3@university.edu,Web Development,On Leave
3,4,Dr. Avery Taylor,prof4@university.edu,"Internet of Things, Database Systems",Busy
4,5,Dr. Casey Brown,prof5@university.edu,"Cybersecurity, Cloud Computing, Software Engin...",Busy

In [ ]:
df["expertise_domains"] = df["expertise_domains"].apply(lambda x: x.split(","))
df.head()

,professor_id,name,email,expertise_domains,availability
0,1,Dr. Blake Williams,prof1@university.edu,"[Software Engineering, Machine Learning, Int...",Available
1,2,Dr. Riley Rodriguez,prof2@university.edu,"[Data Science, Blockchain, Computer Vision]",Available
2,3,Dr. Avery Moore,prof3@university.edu,[Web Development],On Leave
3,4,Dr. Avery Taylor,prof4@university.edu,"[Internet of Things, Database Systems]",Busy
4,5,Dr. Casey Brown,prof5@university.edu,"[Cybersecurity, Cloud Computing, Software En...",Busy

In [ ]:
def recommend_mentors(predicted_domains, top_n=5):

    recommendations = []

    for index, row in df.iterrows():

        professor_domains = [d.strip() for d in row["expertise_domains"]]

        # Calculate matching score
        score = len(set(predicted_domains) & set(professor_domains))

        if score > 0 and row["availability"] == "Available":
            recommendations.append((row["name"], professor_domains, score))

    recommendations.sort(key=lambda x: x[2], reverse=True)

    return recommendations[:top_n]

In [ ]:
domains = ["Machine Learning", "Data Science"]

recommend_mentors(domains)

[('Dr. Cameron Garcia',
  ['Data Science', 'Machine Learning', 'Software Engineering'],
  2),
 ('Dr. Blake Williams',
  ['Software Engineering', 'Machine Learning', 'Internet of Things'],
  1),
 ('Dr. Riley Rodriguez', ['Data Science', 'Blockchain', 'Computer Vision'], 1),
 ('Dr. Jordan Miller', ['Machine Learning', 'Cybersecurity'], 1),
 ('Dr. Robin Gonzalez', ['Machine Learning', 'Computer Vision'], 1)]